version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: deps
    command: npm run start:dev
    container_name: twitter_backend
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo/twitter
    ports:
      - 3333:3333
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      target: deps
    command: yarn dev
    container_name: twitter_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_GRAPHQL_URI_AUTHORITY: localhost:3333
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules/

  mongo:
    container_name: twitter_mongo
    image: mongo
    ports:
      - 27017:27017
