name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
  push:
    branches:
      - main
    paths:
      - 'backend/**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run code formatter
        run: npm run format

      - name: Run linter
        run: npm run lint

      - name: Build source code
        run: npm run build --if-present

      - name: Run tests
        run: npm test --ci --passWithNoTests

      - name: Push to Heroku
        if: github.ref_name == 'main'
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git origin/main:main
