name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

  push:
    branches:
      - main
    paths:
      - 'frontend/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Check types
        run: yarn type-check

      - name: Run tests
        run: npx jest --ci --passWithNoTests

      - name: Build webapp
        run: yarn build
