name: Publish mobile preview from PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'mobile/**'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: mobile

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: mobile/yarn.lock

      - name: Set up Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run all tests
        run: npx jest --ci --passWithNoTests

      - name: Publish preview
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: Comment preview
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: '# Preview release channel "pr-${{ github.event.number }}"\nOpen the camera app on your device and scan the code below\n<img src="https://qr.expo.dev/expo-go?owner=${{ github.repository_owner }}&slug=${{ github.event.repository.name }}&releaseChannel=pr-${{ github.event.number }}" height="200px" width="200px">\nOr, open this [link](exp://exp.host/@${{ github.repository_owner }}/${{ github.event.repository.name }}?release-channel=pr-${{ github.event.number }}) on your device.'
